### ISSUE TITLE
Publish as a rubygem

### ISSUE THREAD

**Issue by zeke** [dkhamsing/frankenstein#7]
https://rubygems.org/gems/frankenstein looks available!

**Comment by dkhamsing** [comment]
Yea it does, it's on my long list of todos.. do you have any tips for that process?

**Comment by zeke** [comment]
Bundler has a command for setting up a new gem. See `bundle help gem` for the details.

**Comment by dkhamsing** [comment]
Thanks

**Comment by dkhamsing** [comment]
@zeke got a quick question.. does Bundler take care of my executables (chmod and add them to path)? Kinda confused about that

**Comment by zeke** [comment]
I think you just need to specify `executables` in the gemspec file. Here's an example from the last CLI gem I wrote (been a while): https://github.com/zeke/rainfall/blob/master/rainfall.gemspec#L10

**Comment by dkhamsing** [comment]
thanks

**Comment by bkuhlmann** [comment]
+1 for publishing this as a RubyGem. [Gemsmith](https://github.com/bkuhlmann/gemsmith) would make the automation of publishing this gem in a consistent manner much easier. I'd also be interested in adding Frankenstein as part of the Gemsmith build process so that if links are detected to be outdated, the gem build fails (but this can be a separate discussion). If you'd want Gemsmith support for Frankenstein, let me know and I can schedule some time to get a PR put together for you.

**Comment by dkhamsing** [comment]
@bkuhlmann thanks.. planning on this when it is more stable.. :smile:

**Comment by dkhamsing** [comment]
The portion that checks links was moved to https://github.com/dkhamsing/awesome_bot
